version: '2'

services:
  web:
    image: datacite/akita
    build: .
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.datacite.org
      - NEXT_PUBLIC_PROFILES_URL=https://profiles.stage.datacite.org
    ports:
      - "9090:80"
    volumes:
      - ./public:/home/app/webapp/public
      - ./.next:/home/app/webapp/.next
      - ./vendor:/home/app/webapp/vendor
