about_links:
 - name: What we do
   url: /value.html
 - name: Governance
   url: /governance.html
 - name: Members
   url: /members.html
 - name: Steering groups
   url: /steering.html
 - name: Staff
   url: /staff.html
 - name: Job opportunities
   url: /jobopportunities.html
services_links:
 - name: Assign DOIs
   url: /dois.html
 - name: Metadata search
   url: /search.html
 - name: Event data
   url: /eventdata.html
 - name: Profiles
   url: /profiles.html
 - name: re3data
   url: /re3data.html
 - name: Citation formatter
   url: /citation.html
 - name: Statistics
   url: /stats.html
 - name: Service status
   url: /service.html
 - name: Content negotiation
   url: /content.html
 - name: OAI-PMH
   url: /oaipmh.html
 - name: Test environment
   url: /test.html
resources_links:
 - name: Metadata schema
   url: https://schema.datacite.org
 - name: Support
   url: https://support.datacite.org
 - name: Fee Model
   url: /feemodel.html
community_links:
 - name: Members
   url: /members.html
 - name: Partners
   url: /partners.html
 - name: Steering groups
   url: /steering.html
 - name: Service providers
   url: /service-providers.html
 - name: Roadmap
   url: /roadmap.html
contact_links:
 - name: Imprint
   url: /imprint.html
 - name: Terms and conditions
   url: /terms.html
 - name: Privacy policy
   url: /privacy.html
