name: Manually Test and Deploy Branch to Vercel
permissions:
  contents: read
on: workflow_dispatch
jobs:
  test:
    uses: ./.github/workflows/cypress_tests.yml
    secrets: inherit
  deploy:
    needs: test
    uses: ./.github/workflows/vercel_deploy.yml
    with:
      production: false
    secrets: inherit
