name: Test Pull Request
permissions:
  contents: read
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    uses: ./.github/workflows/cypress_tests.yml
    secrets: inherit
  deploy:
    if: github.actor != 'dependabot[bot]'
    needs: test
    uses: ./.github/workflows/vercel_deploy.yml
    with:
      production: false
      aliases: |
        commons-pr-${{ github.event.pull_request.number }}.datacite.vercel.app
    secrets: inherit
