name: Test Pull Request
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    uses: ./.github/workflows/cypress_tests.yml
    secrets:
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      CYPRESS_USER_COOKIE: ${{ secrets.CYPRESS_USER_COOKIE }}
