name: Release to Production
permissions:
  contents: read
on:
  release:
    types: [published]
jobs:
  test:
    uses: ./.github/workflows/cypress_tests.yml
    secrets: inherit
  release:
    needs: test
    uses: ./.github/workflows/vercel_deploy.yml
    with:
      production: true
    secrets: inherit
